server:
  port: 8082

spring:
  datasource:
    sell:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://121.40.18.251:3306/SELL?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password: Lm180226~
      initial-size: 5
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package:
